readme; init script tweaks

diff --git a/py-insitu/bin/py-install b/py-insitu/bin/py-install
--- a/py-insitu/bin/py-install
+++ b/py-insitu/bin/py-install
@@ -1,16 +1,20 @@
 #!/bin/bash
 
 # Created by argbash-init v2.10.0
-# DEFINE_SCRIPT_DIR([])
-# ARG_OPTIONAL_BOOLEAN([rebuild-script])
-# ARG_OPTIONAL_BOOLEAN([info])
-# ARG_OPTIONAL_BOOLEAN([make])
-# ARG_OPTIONAL_BOOLEAN([download])
-# ARG_OPTIONAL_BOOLEAN([install])
-# ARG_OPTIONAL_BOOLEAN([install-env])
-# ARG_OPTIONAL_BOOLEAN([dry-run])
-# ARG_HELP([<The general help message of my script>])
-# ARGBASH_GO()
+# DEFINE_SCRIPT_DIR([_script_dir])
+#
+# ARG_OPTIONAL_BOOLEAN([dry-run],[],[Display Commands])
+#
+# ARG_OPTIONAL_ACTION([info],[],[Show python install info],[show_paths])
+# ARG_OPTIONAL_ACTION([make],[],[Configure/Make python],[make_pytho])
+# ARG_OPTIONAL_ACTION([download],[],[Download/Unpack Python *.tgz],[download_python])
+# ARG_OPTIONAL_ACTION([install-python],[],[Install python to .local/python/],[install_python])
+# ARG_OPTIONAL_ACTION([install-env],[],[Install env to .local/envs/],[install_env])
+# ARG_OPTIONAL_ACTION([all],[],[Download/Make/Install/Setup Everything],[run_all])
+#
+# ARG_HELP([<Python/virtual env download/make/install>])
+#
+# ARGBASH_PREPARE()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
@@ -34,19 +38,20 @@ begins_with_short_option()
 }
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_rebuild_script="off"
-_arg_info="off"
-_arg_make="off"
-_arg_download="off"
-_arg_install="off"
-_arg_install_env="off"
 _arg_dry_run="off"
 
 
 print_help()
 {
-	printf '%s\n' "<The general help message of my script>"
-	printf 'Usage: %s [--(no-)rebuild-script] [--(no-)info] [--(no-)make] [--(no-)download] [--(no-)install] [--(no-)install-env] [--(no-)dry-run] [-h|--help]\n' "$0"
+	printf '%s\n' "<Python/virtual env download/make/install>"
+	printf 'Usage: %s [--(no-)dry-run] [--info] [--make] [--download] [--install-python] [--install-env] [--all] [-h|--help]\n' "$0"
+	printf '\t%s\n' "--dry-run, --no-dry-run: Display Commands (off by default)"
+	printf '\t%s\n' "--info: Show python install info"
+	printf '\t%s\n' "--make: Configure/Make python"
+	printf '\t%s\n' "--download: Download/Unpack Python *.tgz"
+	printf '\t%s\n' "--install-python: Install python to .local/python/"
+	printf '\t%s\n' "--install-env: Install env to .local/envs/"
+	printf '\t%s\n' "--all: Download/Make/Install/Setup Everything"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -57,33 +62,33 @@ parse_commandline()
 	do
 		_key="$1"
 		case "$_key" in
-			--no-rebuild-script|--rebuild-script)
-				_arg_rebuild_script="on"
-				test "${1:0:5}" = "--no-" && _arg_rebuild_script="off"
-				;;
-			--no-info|--info)
-				_arg_info="on"
-				test "${1:0:5}" = "--no-" && _arg_info="off"
-				;;
-			--no-make|--make)
-				_arg_make="on"
-				test "${1:0:5}" = "--no-" && _arg_make="off"
-				;;
-			--no-download|--download)
-				_arg_download="on"
-				test "${1:0:5}" = "--no-" && _arg_download="off"
-				;;
-			--no-install|--install)
-				_arg_install="on"
-				test "${1:0:5}" = "--no-" && _arg_install="off"
-				;;
-			--no-install-env|--install-env)
-				_arg_install_env="on"
-				test "${1:0:5}" = "--no-" && _arg_install_env="off"
-				;;
 			--no-dry-run|--dry-run)
 				_arg_dry_run="on"
 				test "${1:0:5}" = "--no-" && _arg_dry_run="off"
+				;;
+			--info)
+				show_paths
+				exit 0
+				;;
+			--make)
+				make_pytho
+				exit 0
+				;;
+			--download)
+				download_python
+				exit 0
+				;;
+			--install-python)
+				install_python
+				exit 0
+				;;
+			--install-env)
+				install_env
+				exit 0
+				;;
+			--all)
+				run_all
+				exit 0
 				;;
 			-h|--help)
 				print_help
@@ -101,86 +106,21 @@ parse_commandline()
 	done
 }
 
-parse_commandline "$@"
 
 # OTHER STUFF GENERATED BY Argbash
-script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
+_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
 
 # shellcheck disable=2154
+readonly script_dir="$_script_dir"
+
+source "$script_dir/_utils.sh"
+
+# shellcheck disable=2154
 source "$script_dir/paths.sh"
-
-# shellcheck disable=2154
-info=$_arg_info
-
-# shellcheck disable=2154
-rebuild_script=$_arg_rebuild_script
-
-# shellcheck disable=2154
-dryrun=$_arg_dry_run
-
-# shellcheck disable=2154
-download=$_arg_download
-
-# shellcheck disable=2154
-arg_make=$_arg_make
-
-# shellcheck disable=2154
-install=$_arg_install
-
-# shellcheck disable=2154
-install_env=$_arg_install_env
-
-
-doit() {
-    local cmds=("$@")
-    if [ "$dryrun" = on ]; then
-        echo "dry> ${cmds[*]}"
-    else
-        echo "run> ${cmds[*]}"
-        "${cmds[@]}"
-    fi
-
-    echo ""
-}
-
-with_dirs() {
-    local dirnames=("$@")
-    for d in "${dirnames[@]}"; do
-        if [ ! -d "$d" ]; then
-            echo "could not cd to '$d' in ${dirnames[*]}"
-            exit 1
-        fi
-        cd "$d" || exit 1
-    done
-    echo "In dir: $(pwd)"
-}
-
-do_rebuild_script() {
-    echo "Rebuilding script.."
-    with_dirs "$script_dir"
-    argbash py-install.m4 -o py-install
-    exit 0
-}
-
-download_python() {
-    echo "Download Python $PYVER"
-    with_dirs "$INSTALL_TMPD"
-    if [ ! -f "$PYTGZ" ]; then
-        echo "No $PYTGZ found, downloading"
-        doit wget "$PYSRC_URL"
-    fi
-    if [ ! -f "$PYTGZ" ]; then
-        echo "Could not download Python from $PYSRC_URL"
-        exit 1
-    fi
-    if [ -f "$PYTGZ" ]; then
-        echo "$PYTGZ downloaded"
-    fi
-}
 
 unpack_python() {
     echo "Unpacking Python $PYVER"
@@ -198,6 +138,23 @@ unpack_python() {
     else
         echo "Unpacked Python $PYSRC"
     fi
+}
+
+download_python() {
+    echo "Download Python $PYVER"
+    with_dirs "$INSTALL_TMPD"
+    if [ ! -f "$PYTGZ" ]; then
+        echo "No $PYTGZ found, downloading"
+        doit wget "$PYSRC_URL"
+    fi
+    if [ ! -f "$PYTGZ" ]; then
+        echo "Could not download Python from $PYSRC_URL"
+        exit 1
+    fi
+    if [ -f "$PYTGZ" ]; then
+        echo "$PYTGZ downloaded"
+    fi
+    unpack_python
 }
 
 make_python() {
@@ -229,29 +186,20 @@ install_env() {
     doit "$PYTHOND/bin/virtualenv" "$ENV_ROOT"
 }
 
-test "$info" = on && show_paths && exit 0
-test "$rebuild_script" = on && do_rebuild_script && exit 0
-
-if [ "$download" = on ]; then
-    echo "Downloading Python"
+run_all() {
+    echo "Running Everything"
     download_python
-    unpack_python
-fi
-
-if [ "$arg_make" = on ]; then
-    echo "Making Python"
     make_python
-fi
-
-if [ "$install" = on ]; then
-    echo "Installing Python"
     install_python
-fi
-
-if [ "$install_env" = on ]; then
-    echo "(Re)installing Env"
     install_env
-fi
+}
 
+#########################
+## Run Main
+#########################
+parse_commandline "$@"
+
+## Print help if no other action has been taken
+_PRINT_HELP=yes die "" 1
 
 # ] <-- needed because of Argbash
